package com.example.demo.service;

import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.cache.annotation.Cacheable;
import org.springframework.stereotype.Service;

import com.example.demo.dao.UserRepository;
import com.example.demo.model.User;

@Service
public class UserService {

	@Autowired // This means to get the bean called userRepository
	// Which is auto-generated by Spring, we will use it to handle
	// the data
	private UserRepository userRepository;
	public List<User> getAllUers() {
		List<User> users=userRepository.findAll();
		return users;
	}

	public User getUserByid(Integer id) {
		// TODO Auto-generated method stub
		return userRepository.findOne(id);
	}

	public User saveUser(User user) {
		// TODO Auto-generated method stub
		return userRepository.save(user);
	}

	public User updateUser(User user) {
		// TODO Auto-generated method stub
		return userRepository.save(user);
	}

	public String deleteUser(Integer id) {
		// TODO Auto-generated method stub
		userRepository.delete(id);
		return "User Deleted";
	}

}
